-- Generated by the database client.
CREATE TABLE cctv_streams(
    id SERIAL NOT NULL,
    floor_id integer NOT NULL,
    name varchar(100) NOT NULL,
    url text NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    PRIMARY KEY(id),
    CONSTRAINT cctv_streams_floor_id_fkey FOREIGN key(floor_id) REFERENCES floors(id)
);
CREATE INDEX idx_cctv_floor_id ON public.cctv_streams USING btree (floor_id);
CREATE INDEX idx_cctv_active ON public.cctv_streams USING btree (is_active);
COMMENT ON TABLE cctv_streams IS 'Menyimpan URL stream CCTV per lantai';