-- Generated by the database client.
CREATE TABLE floors(
    id SERIAL NOT NULL,
    name varchar(100) NOT NULL,
    number integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    PRIMARY KEY(id)
);
COMMENT ON TABLE floors IS 'Menyimpan informasi lantai gedung';