-- Generated by the database client.
CREATE TABLE tables(
    id SERIAL NOT NULL,
    name varchar(100) NOT NULL,
    floor_id integer NOT NULL,
    capacity integer NOT NULL DEFAULT 1,
    status varchar(20) NOT NULL DEFAULT 'available'::character varying,
    coords jsonb,
    width double precision,
    height double precision,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    rotation double precision DEFAULT 0.0,
    PRIMARY KEY(id),
    CONSTRAINT tables_floor_id_fkey FOREIGN key(floor_id) REFERENCES floors(id)
);
CREATE INDEX idx_tables_floor_id ON public.tables USING btree (floor_id);
CREATE INDEX idx_tables_status ON public.tables USING btree (status);
COMMENT ON TABLE tables IS 'Menyimpan informasi meja dengan koordinat dan dimensi untuk deteksi';
COMMENT ON COLUMN tables.coords IS 'Koordinat meja dalam format [x_min, y_min, x_max, y_max] atau {x, y, width, height}';
COMMENT ON COLUMN tables.width IS 'Lebar meja dalam pixel, auto-calculated dari coords';
COMMENT ON COLUMN tables.height IS 'Tinggi meja dalam pixel, auto-calculated dari coords';